language: node_js
node_js: v12
addons:
  chrome: stable
before_install:
  - npm install -g @lhci/cli@0.3.x
  - npm install -g lighthouse
  - npm install -g lighthouse-plugin-field-performance
script:
  - export LHCI_BUILD_CONTEXT__CURRENT_HASH=$(head -n 4096 /dev/urandom | openssl sha1 | sed 's/(stdin)=//g' | fold -w 8 | head -n 1)
  - export LHCI_BUILD_CONTEXT__COMMIT_TIME=$(date +%Y-%m-%dT%H:%M:%S%z)
  - export LHCI_BUILD_CONTEXT__CURRENT_BRANCH=master
  - export LHCI_BUILD_CONTEXT__COMMIT_MESSAGE="Periodic run"
  - export LHCI_BUILD_CONTEXT__AUTHOR="Liccy Fuentes <liccy.fuentes@daily-harvest.com>"
  - export LHCI_BUILD_CONTEXT__AVATAR_URL="https://picsum.photos/id/870/200/200"
  - lhci autorun --upload.token="$LHCI_UPLOAD__TOKEN" # run lighthouse CI
env:
  global: 
    - secure: "lEI2AT2W1otIDWct1c5zy5d6mnZBAW+wGCHqjdor+HjIwt1yOlAdZCZr294L9MMjzuTuxUr3sk4KzkoZKNaqwCLY9inDDJD4u5uvLhuonDn+kI4wcSlPgAFGvsPLZ5DyoSwAUwq5lmMWCV+b2EmXI2bExnHLoEB4wnuy0Aq7bhAqnDJmDtE5y5F/+RU99hxGRfzgHbNMC6KftBIIM2CBD70S0gOmwvrowzc1NQMpwJEMt0j7/8fZOX6bpy67HpG+p9WYfB7ntnVigCHZ8DlcLHHyRqFr/Z0qRkFUCh6OogLmurJGTnQyUiTx02IzVhxzGhQIfw7TDfnPtAZMRY1dMT3lKOjGuoq5b1dnLpiMF3lGu8hleX75bAMD7ioN7mvEdvkG4VRrz1oNgKU7ZU9oMcH6pxtwXspieX7/ZvV/cLyMf2261na5ow0cQB44qMd0PXE79OEFe7/Dq7jHPkeCSOiFyjuA2Wklm5ecigIzOLkD/PVEueOQzckb9Ap+PoDbAZzSkiuFCDjEA9lB7Ln1FXvoW+zsnhD4g0psJloZmj5um5jlAC0ye6j38QXSbIfcNtqa+3I/9Z+sgDagj36yPdwhrNGz/mEByCoIGrpmGuo+rVKtO3gpYbNWM4I52e2Cb5RbWlaiz+GJ2DVKeyUll0H679fpLbdPagxFwm1YBIo="
